{
 "title": "水费/电费/燃气",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "year",
    "query": "select distinct year from yearlyxxxxxxxxxxxxx"
   }
  ]
 },
 "panels": [
  { "title": "燃气费", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "燃气总费用",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "￥" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "  SELECT sum(money) from  shrq_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "rawQueryText": "  SELECT sum(money) from  shrq_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "燃气总用量",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "  SELECT yearConsumption from  shrq_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "rawQueryText": "  SELECT yearConsumption from  shrq_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "本期燃气费",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "￥" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "  SELECT money from  shrq_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "rawQueryText": "  SELECT money from  shrq_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "当前燃气梯度单价",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "￥/立方" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "  SELECT price from  shrq_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "rawQueryText": "  SELECT price from  shrq_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "燃气本期用气量",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "  SELECT consumption from  shrq_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "rawQueryText": "  SELECT consumption from  shrq_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "燃气本期抄表数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "  SELECT currentReading from  shrq_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "rawQueryText": "  SELECT currentReading from  shrq_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "$year年-月度数据燃气/CNY",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "repeat": "year",
   "fieldConfig": { "defaults": { "unit": "￥" } },
   "targets": [
    {
     "queryText": "SELECT \r\n    SUBSTR(date, 1, 7) AS \"日期\",\r\n    money AS \"金额/CNY\"\r\nFROM \r\n    shrq_billxxxxxxx\r\nWHERE \r\n    date LIKE '${year}-%'\r\nORDER BY \r\n    date ASC",
     "rawQueryText": "SELECT \r\n    SUBSTR(date, 1, 7) AS \"日期\",\r\n    money AS \"金额/CNY\"\r\nFROM \r\n    shrq_billxxxxxxx\r\nWHERE \r\n    date LIKE '${year}-%'\r\nORDER BY \r\n    date ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "$year年-月度数据燃气/立方",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "repeat": "year",
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "queryText": "SELECT \r\n    SUBSTR(date, 1, 7) AS \"日期\",\r\n    consumption AS \"用量/立方\"\r\nFROM \r\n    shrq_billxxxxxxx\r\nWHERE \r\n    date LIKE '${year}-%'\r\nORDER BY \r\n    date ASC",
     "rawQueryText": "SELECT \r\n    SUBSTR(date, 1, 7) AS \"日期\",\r\n    consumption AS \"用量/立方\"\r\nFROM \r\n    shrq_billxxxxxxx\r\nWHERE \r\n    date LIKE '${year}-%'\r\nORDER BY \r\n    date ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "水费", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "总用水量",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "  SELECT sum(waternum) + sum(dirtynum) from  pdwly_billxxxxxxx where date LIKE '${year}-%' ",
     "rawQueryText": "  SELECT sum(waternum) + sum(dirtynum) from  pdwly_billxxxxxxx where date LIKE '${year}-%' ",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "本期总水费",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "￥" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "  SELECT sumpay from  pdwly_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "rawQueryText": "  SELECT sumpay from  pdwly_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "本期生活水费",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "￥" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "  SELECT waterfee from  pdwly_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "rawQueryText": "  SELECT waterfee from  pdwly_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "本期污水费",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "￥" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "  SELECT dirtyfee from  pdwly_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "rawQueryText": "  SELECT dirtyfee from  pdwly_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "本期生活用水单价",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "￥/立方" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "  SELECT waterprice from  pdwly_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "rawQueryText": "  SELECT waterprice from  pdwly_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "本期污水用水单价",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "￥/立方" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "  SELECT dirtyprice from  pdwly_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "rawQueryText": "  SELECT dirtyprice from  pdwly_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "水费总费用",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "￥" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "  SELECT sum(sumpay) from  pdwly_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "rawQueryText": "  SELECT sum(sumpay) from  pdwly_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "水表本期抄表数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "  SELECT waternum + dirtynum from  pdwly_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "rawQueryText": "  SELECT waternum + dirtynum from  pdwly_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "本期生活用水量",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "  SELECT waternum from  pdwly_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "rawQueryText": "  SELECT waternum from  pdwly_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "本期污水用水量",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "  SELECT dirtynum from  pdwly_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "rawQueryText": "  SELECT dirtynum from  pdwly_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "下一期账单日",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "  SELECT nextdate from  pdwly_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "rawQueryText": "  SELECT nextdate from  pdwly_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "本期账单状态",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "  SELECT billstatus from  pdwly_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "rawQueryText": "  SELECT billstatus from  pdwly_billxxxxxxx where date LIKE '${year}-%' ORDER by date desc limit 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "$year年-年度水费/CNY",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "repeat": "year",
   "fieldConfig": { "defaults": { "unit": "￥" } },
   "targets": [
    {
     "queryText": "SELECT \r\n    SUBSTR(date, 1, 7) AS \"日期\",\r\n    sumpay AS \"金额/￥\"\r\nFROM \r\n    pdwly_billxxxxxxx\r\nWHERE \r\n    date LIKE '${year}-%'\r\nORDER BY \r\n    date ASC",
     "rawQueryText": "SELECT \r\n    SUBSTR(date, 1, 7) AS \"日期\",\r\n    sumpay AS \"金额/￥\"\r\nFROM \r\n    pdwly_billxxxxxxx\r\nWHERE \r\n    date LIKE '${year}-%'\r\nORDER BY \r\n    date ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "$year年-年度水用量/立方",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "repeat": "year",
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "queryText": "SELECT \r\n    SUBSTR(date, 1, 7) AS \"日期\",\r\n    (waternum + dirtynum) AS \"用量/立方\"\r\nFROM \r\n    pdwly_billxxxxxxx\r\nWHERE \r\n    date LIKE '${year}-%'\r\nORDER BY \r\n    date ASC",
     "rawQueryText": "SELECT \r\n    SUBSTR(date, 1, 7) AS \"日期\",\r\n    (waternum + dirtynum) AS \"用量/立方\"\r\nFROM \r\n    pdwly_billxxxxxxx\r\nWHERE \r\n    date LIKE '${year}-%'\r\nORDER BY \r\n    date ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "电费", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "本期电费",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "￥" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "  SELECT charge from  monthlyxxxxxxxxxxxxx where month LIKE '${year}-%' ORDER by month desc limit 1",
     "rawQueryText": "  SELECT charge from  monthlyxxxxxxxxxxxxx where month LIKE '${year}-%' ORDER by month desc limit 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "本期用电量",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "  SELECT usage from  monthlyxxxxxxxxxxxxx where month LIKE '${year}-%' ORDER by month desc limit 1",
     "rawQueryText": "  SELECT usage from  monthlyxxxxxxxxxxxxx where month LIKE '${year}-%' ORDER by month desc limit 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "$year年 - 年度电费账单",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 47 },
   "repeat": "year",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT year as \"年份\",usage as \"电/KWh\",charge as \"电/￥\" from yearlyxxxxxxxxxxxxx   where year in (${year:csv})\r\n\r\n\r\n",
     "rawQueryText": "SELECT year as \"年份\",usage as \"电/KWh\",charge as \"电/￥\" from yearlyxxxxxxxxxxxxx   where year in (${year:csv})\r\n\r\n\r\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "$year年-月度数据电量/费",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "repeat": "year",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT SUBSTR(month, 1, 10) AS \"月份\", usage as \"电量/kWh\", charge as \"金额/CNY\"  from  monthlyxxxxxxxxxxxxx where month LIKE '${year}-%' order by month asc",
     "rawQueryText": "SELECT SUBSTR(month, 1, 10) AS \"月份\", usage as \"电量/kWh\", charge as \"金额/CNY\"  from  monthlyxxxxxxxxxxxxx where month LIKE '${year}-%' order by month asc",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "$year年-月度数据电量/费",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
   "repeat": "year",
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "queryText": "SELECT \r\n    SUBSTR(date, 1, 10) AS \"日期\",\r\n    usage AS \"电量/kWh\"\r\nFROM \r\n    dailyxxxxxxxxxxxxx\r\nWHERE \r\n    date LIKE '${year}-%'\r\nORDER BY \r\n    date ASC",
     "rawQueryText": "SELECT \r\n    SUBSTR(date, 1, 10) AS \"日期\",\r\n    usage AS \"电量/kWh\"\r\nFROM \r\n    dailyxxxxxxxxxxxxx\r\nWHERE \r\n    date LIKE '${year}-%'\r\nORDER BY \r\n    date ASC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}